config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "home" => "static_pages#home"
  get "game" => "static_pages#game"

  resources :scores, only: [ :index, :create, :new ]
end

app/models/score.rb
class Score < ActiveRecord::Base
	scope :best_ten, ->() {
		Score.order(:time).first(10)
	}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
	

	def index
		@scores = Score.best_ten
	end

	def new
		@score = Score.new
		respond_to do |format|
			format.html { redirect_to root_url }
			format.js { render layout: false }
		end
	end

	def create
		@score = Score.create(score_params)
		redirect_to scores_path
	end


	private

	def score_params
		params.require(:score).permit(:time, :name)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def game
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mine Hunter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav>
		<h1>Mine Hunter</h1>
		<h2> - by Cyprium - </h2>
		<div id="links">
				<div class="item"><%= link_to "About", home_path %></div>
				<div class="item"><%= link_to "Game", game_path %></div>
				<div class="item"><%= link_to "Scores", scores_path %></div>
		</div>
	</nav>
		<%= yield %>

</body>
</html>

app/views/scores/_form.html.erb
<%= form_for @score do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit "Submit" %>
	<%= f.hidden_field :time, value: 999 %>
<% end %>

app/views/scores/index.html.erb
<article>
	<h1>Here are the top players of the game</h1>
	<table>
		<tr>
			<th>Player name</th>
			<th>Score</th>
		</tr>
		<% 10.times do |i| %>
		<tr>
			<% if(!@scores[i].nil?) %>
				<td><%= @scores[i].name %></td>
				<td><%= @scores[i].time %></td>
			<% else %>
				<td>n/a</td>
				<td>n/a</td>
			<% end %>
		</tr>
		<% end %>
	</table>
</article>

app/views/scores/new.js.erb
// TODO: Check if the time has been tampered with

$("#score-form").html("<%= j( render 'form') %>").hide();
$("#score-form").show(1000);
var time = parseInt($("time").text());
$("#score_time").val(time);

app/views/static_pages/game.html.erb
<div id="score-form-link">
	<%= link_to "Connect to Server", new_score_path, remote: true %>
</div>

<div id="score-form"></div>
<div id="game">
	<span id="time">Time: <time>n/a</time></span>
	<h1 class="ui">Welcome to Mine Hunter!</h1>
	<button class="ui" id="start">New Game</button>
	<h2>Mine count: <span id="mines">n/a</span></h2>
	<h3 class="ui">How to play:</h3>
	<p class="ui">Click with LMB to reveal field</p>
	<p class="ui">Shift+Click to place a flag</p>
</div>

app/views/static_pages/home.html.erb
<article>
	<h1>Welcome to my first web project</h1>
	<p>Hi. My name is Stefan Kupresak ( also known as Cyprium ), and currently I'm first grade student of Computer Science. I have a lot of passion for web development so I took the <a href=""> The Odin Project</a> ( a free web design/programming course ). This is my first attempt to create something on my own with the stuff I've learned there.</p>
	<h1>About &amp; GitHub</h1>
	<p>This application was made in Rails framework, jQuery( for the game), html5 and SASS(css pre-processor) and it's completley open-source.</p>
	<p>You can find it in a repository on github and you can find it <a href="https://github.com/dev-cyprium/Mine-Hunter">here.</a></p>
	<h1>Contact</h1>
	<p>You can get in touch with me: </p>
	<ul>
		<li>Email: <em>stefan_vg@hotmail.com</em></li>
		<li>GitHub: <a href="https://github.com/dev-cyprium">link</a></li>
		<li>Slack(username -> Cyprium): <a href="https://theodinproject.slack.com/messages/general/details/">link</a></li>
	</ul>
</article>